---
name: CI

on:
  push:
    branches: [ "main", "feat/*", "release/*" ]
  pull_request:
    branches: [ "main", "feat/*", "release/*" ]
  schedule:
    - cron: '0 2 * * 1' # https://crontab.guru/#0_2_*_*_1

permissions:
  contents: read

jobs:
  lint-yaml:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run yamllint
        uses: ibiqlik/action-yamllint@v3

  lint-folders:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run folderslint in container
        run: docker run -i --rm --volume "$(pwd):$(pwd)" --workdir "$(pwd)" sommerfeldio/folderslint:latest folderslint

  lint-filenames:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run ls-lint in container
        run: docker run -i --rm --volume "$(pwd):/data" --workdir "/data" lslintorg/ls-lint:1.11.0

  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          ignore_paths: node_modules target

  lint-actions-dockerfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: hadolint
        uses: hadolint/hadolint-action@v2.0.0
        with:
          dockerfile: src/main/action/Dockerfile

  lint-baseimage-dockerfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: hadolint
        uses: hadolint/hadolint-action@v2.0.0
        with:
          dockerfile: src/main/baseimage/Dockerfile

  ci-build:
    runs-on: ubuntu-latest
    needs: ['lint-actions-dockerfile', 'lint-baseimage-dockerfile']
    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set docker tag ('ci-build' for main or feature branch, 'release-candidate' for release branch)
        id: vars
        run: |
          echo ${{ github.ref }}

          TAG='ci-build'
          REF='refs/heads/release/'

          if [[ ${{ github.ref }} == *${REF}* ]]; then
            TAG='release-candidate'
          fi

          echo "tag = $TAG"
          echo "DOCKER_TAG=$TAG" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker image build (baseimage 'sommerfeldio/shdoc')
        uses: docker/build-push-action@v3
        with:
          context: ./src/main/baseimage
          platforms: linux/amd64
          push: true
          tags: sommerfeldio/shdoc:${{ steps.vars.outputs.DOCKER_TAG }}

      - name: Run container and print versions of installed packages
        run: |
          docker pull sommerfeldio/shdoc:${{ steps.vars.outputs.DOCKER_TAG }}
          # docker run -i sommerfeldio/adoc-antora:${{ steps.vars.outputs.DOCKER_TAG }} ...

      - name: Run Snyk to check Docker image for vulnerabilities
        continue-on-error: true
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: sommerfeldio/adoc-antora:${{ steps.vars.outputs.DOCKER_TAG }}
          args: --file=src/main/baseimage/Dockerfile

      - name: Upload snyk result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif

      - name: Docker image build (actions image)
        uses: docker/build-push-action@v3
        with:
          context: ./src/main/action
          platforms: linux/amd64
          push: false

  on-failure:
    runs-on: ubuntu-latest
    needs: ['ci-build', 'lint-yaml', 'lint-folders', 'lint-filenames', 'shellcheck', 'lint-actions-dockerfile', 'lint-baseimage-dockerfile']
    if: failure()

    steps:
      - name: Send Pipeline Status to Google Chat
        if: always()
        uses: Co-qn/google-chat-notification@releases/v1
        with:
          name: ${{ github.workflow }}
          url: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}
          status: failure
